/**
 * DuoSign Extension — YouTube Caption Interceptor & PiP Overlay
 * ==============================================================
 * Architecture:
 *   1. MutationObserver watches .ytp-caption-segment for live caption text
 *   2. Phrase buffer flushes on punctuation boundary OR 1.5s silence gap
 *   3. Buffered phrase is sent to background via chrome.runtime.sendMessage (TRANSLATE)
 *   4. Background translates → returns ASL gloss tokens
 *   5. PosePlayer fetches .pose files from Supabase, plays them via drawSkeleton
 *   6. Rendered on a draggable PiP canvas overlay inside the YouTube player
 */

(function () {
  // Guard against multiple injections (e.g. SPA nav re-runs)
  if (window.__duosignYT) return;
  window.__duosignYT = true;

  // ── Constants ────────────────────────────────────────────────────────────
  const PHRASE_SILENCE_MS   = 1500;   // flush after this many ms of no new caption
  const PHRASE_MAX_CHARS    = 200;    // hard cap to avoid calling NLP on huge chunks
  const PUNCTUATION_RE      = /[.?!;,]/; // flush on these boundaries
  const PIP_WIDTH           = 260;
  const PIP_HEIGHT          = 320;

  // ── State ────────────────────────────────────────────────────────────────
  let captionObserver   = null;
  let pipElement        = null;
  let bannerElement     = null;
  let isSigningActive   = false;
  let lastCaption       = "";
  let phraseBuffer      = "";
  let silenceTimer      = null;
  let posePlayer        = null;
  let pipCanvas         = null;
  let pipCtx            = null;
  let isDragging        = false;
  let dragOffsetX       = 0;
  let dragOffsetY       = 0;

  // ── Wait for YouTube player ──────────────────────────────────────────────
  function waitForPlayer() {
    return new Promise((resolve) => {
      const check = () => {
        const player = document.querySelector("#movie_player");
        if (player) return resolve(player);
        setTimeout(check, 500);
      };
      check();
    });
  }

  // ── Caption detection ────────────────────────────────────────────────────
  function detectCaptions() {
    const btn = document.querySelector(".ytp-subtitles-button");
    return btn && btn.getAttribute("aria-pressed") !== undefined;
  }

  function isAutoGenerated() {
    const tracks = document.querySelectorAll(".ytp-menuitem-label");
    for (const t of tracks) {
      if (t.textContent?.toLowerCase().includes("auto-generated")) return true;
    }
    return true; // conservative default
  }

  // ── Detection banner ─────────────────────────────────────────────────────
  function createBanner(playerEl) {
    if (bannerElement) return;

    bannerElement = document.createElement("div");
    bannerElement.id = "duosign-yt-banner";
    bannerElement.innerHTML = `
      <div class="duosign-detect-icon">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#2dd4bf" stroke-width="2.5" stroke-linecap="round">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>
        </svg>
      </div>
      <div class="duosign-detect-text">
        <strong>Captions detected</strong> — DuoSign can sign this video
      </div>
      <button class="duosign-detect-action" id="duosignStartBtn">Start Signing</button>
    `;

    const container =
      playerEl.closest("#player-container-outer") ||
      playerEl.closest("#player") ||
      playerEl.parentElement;

    if (container?.parentElement) {
      container.parentElement.insertBefore(bannerElement, container.nextSibling);
    }

    document.getElementById("duosignStartBtn").addEventListener("click", () => {
      if (isSigningActive) stopSigning();
      else startSigning(playerEl);
    });

    if (isAutoGenerated()) {
      const disclaimer = document.createElement("div");
      disclaimer.id = "duosign-yt-disclaimer";
      disclaimer.innerHTML = `
        <span class="duosign-warn-icon">⚠</span>
        <span>Auto-generated captions may contain inaccuracies that affect signing accuracy.</span>
      `;
      bannerElement.after(disclaimer);
    }
  }

  // ── PiP overlay ──────────────────────────────────────────────────────────
  function createPiP(playerEl) {
    if (pipElement) return;

    pipElement = document.createElement("div");
    pipElement.id = "duosign-pip";
    pipElement.innerHTML = `
      <div class="duosign-pip-header" id="duosignPipHeader">
        <div class="duosign-pip-label">
          <span class="duosign-pip-dot"></span>
          SIGNING
        </div>
        <div class="duosign-pip-controls">
          <button class="duosign-pip-btn" id="duosignPipClose" title="Close">×</button>
        </div>
      </div>
      <div class="duosign-pip-canvas-wrap">
        <canvas id="duosignPipCanvas" width="${PIP_WIDTH}" height="${PIP_HEIGHT - 50}"></canvas>
        <div class="duosign-pip-idle" id="duosignPipIdle">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#363a4e" stroke-width="1.5">
            <circle cx="12" cy="8" r="4"/><path d="M4 20c0-4 3.6-7 8-7s8 3 8 7"/>
          </svg>
          <span>Waiting for captions…</span>
        </div>
      </div>
      <div class="duosign-pip-footer">
        <span class="duosign-pip-gloss" id="duosignPipGloss">—</span>
        <span class="duosign-pip-status" id="duosignPipStatus">Ready</span>
      </div>
    `;

    // Attach to player so it's positioned relative to video
    playerEl.appendChild(pipElement);

    // Close
    document.getElementById("duosignPipClose").addEventListener("click", stopSigning);

    // Make draggable via the header
    const header = document.getElementById("duosignPipHeader");
    header.addEventListener("mousedown", onDragStart);

    // Setup canvas
    pipCanvas = document.getElementById("duosignPipCanvas");
    pipCtx    = pipCanvas.getContext("2d");
  }

  // ── Drag logic ───────────────────────────────────────────────────────────
  function onDragStart(e) {
    if (!pipElement) return;
    isDragging   = true;
    const rect   = pipElement.getBoundingClientRect();
    dragOffsetX  = e.clientX - rect.left;
    dragOffsetY  = e.clientY - rect.top;
    pipElement.style.transition = "none";
    e.preventDefault();
  }

  document.addEventListener("mousemove", (e) => {
    if (!isDragging || !pipElement) return;
    const parent = pipElement.parentElement;
    if (!parent) return;
    const parentRect = parent.getBoundingClientRect();
    let x = e.clientX - parentRect.left - dragOffsetX;
    let y = e.clientY - parentRect.top  - dragOffsetY;
    // Clamp inside parent
    x = Math.max(0, Math.min(x, parentRect.width  - PIP_WIDTH));
    y = Math.max(0, Math.min(y, parentRect.height - PIP_HEIGHT));
    pipElement.style.right  = "auto";
    pipElement.style.bottom = "auto";
    pipElement.style.left   = `${x}px`;
    pipElement.style.top    = `${y}px`;
  });

  document.addEventListener("mouseup", () => { isDragging = false; });

  // ── PosePlayer setup ─────────────────────────────────────────────────────
  function initPosePlayer() {
    if (posePlayer) return;

    // PosePlayer, parsePose, drawSkeleton are all loaded via content scripts
    // before this file (see manifest.json order)
    if (typeof PosePlayer === "undefined" || typeof drawSkeleton === "undefined") {
      console.warn("[DuoSign YT] PosePlayer or drawSkeleton not loaded — skeleton unavailable");
      return;
    }

    const cw = PIP_WIDTH;
    const ch = PIP_HEIGHT - 50;

    posePlayer = new PosePlayer({
      onFrame(frame, header) {
        const idle = document.getElementById("duosignPipIdle");
        if (idle) idle.style.display = "none";
        drawSkeleton(pipCtx, frame, header, cw, ch);
      },
      onGlossChange(gloss) {
        const el = document.getElementById("duosignPipGloss");
        if (el) el.textContent = gloss;
      },
      onComplete() {
        setStatus("Ready");
        // Clear canvas to show idle state
        if (pipCtx) pipCtx.clearRect(0, 0, PIP_WIDTH, PIP_HEIGHT);
        const idle = document.getElementById("duosignPipIdle");
        if (idle) idle.style.display = "flex";
        const glossEl = document.getElementById("duosignPipGloss");
        if (glossEl) glossEl.textContent = "—";
      },
      onStateChange(state) {
        setStatus(state === "playing" ? "Signing…" : state === "paused" ? "Paused" : "Ready");
      },
    });
  }

  function setStatus(text) {
    const el = document.getElementById("duosignPipStatus");
    if (el) el.textContent = text;
  }

  // ── Start / stop ─────────────────────────────────────────────────────────
  function startSigning(playerEl) {
    isSigningActive = true;

    const btn = document.getElementById("duosignStartBtn");
    if (btn) {
      btn.textContent = "Stop Signing";
      btn.classList.add("active");
    }

    createPiP(playerEl);
    pipElement.style.display = "block";
    initPosePlayer();
    startCaptionObserver();

    chrome.runtime.sendMessage({ type: "YOUTUBE_START" });
  }

  function stopSigning() {
    isSigningActive = false;
    clearSilenceTimer();

    const btn = document.getElementById("duosignStartBtn");
    if (btn) {
      btn.textContent = "Start Signing";
      btn.classList.remove("active");
    }

    if (pipElement) pipElement.style.display = "none";
    if (captionObserver) { captionObserver.disconnect(); captionObserver = null; }
    if (posePlayer) posePlayer.stop();

    chrome.runtime.sendMessage({ type: "YOUTUBE_STOP" });
  }

  // ── Caption observer ─────────────────────────────────────────────────────
  function startCaptionObserver() {
    const captionRoot =
      document.querySelector(".ytp-caption-window-container") ||
      document.querySelector(".caption-window");

    if (!captionRoot) {
      setTimeout(startCaptionObserver, 1000);
      return;
    }

    captionObserver = new MutationObserver(() => {
      const segments = document.querySelectorAll(".ytp-caption-segment");
      let text = "";
      segments.forEach((s) => { text += s.textContent + " "; });
      text = text.trim();

      if (text && text !== lastCaption) {
        lastCaption = text;
        onCaptionChunk(text);
      }
    });

    captionObserver.observe(captionRoot, {
      childList: true,
      subtree: true,
      characterData: true,
    });
  }

  // ── Phrase buffer ─────────────────────────────────────────────────────────
  // YouTube fires captions word-by-word. We accumulate chunks and flush when:
  //   a) We see a sentence-ending punctuation mark
  //   b) 1.5s passes with no new caption (silence gap)
  //   c) Buffer exceeds PHRASE_MAX_CHARS

  function clearSilenceTimer() {
    if (silenceTimer) { clearTimeout(silenceTimer); silenceTimer = null; }
  }

  function onCaptionChunk(text) {
    if (!isSigningActive) return;

    // Accumulate — avoid appending exact duplicates that YouTube sometimes re-emits
    if (!phraseBuffer.endsWith(text)) {
      phraseBuffer = (phraseBuffer + " " + text).trim();
    }

    // Check punctuation boundary
    const lastChar = phraseBuffer[phraseBuffer.length - 1];
    const endsWithPunct = PUNCTUATION_RE.test(lastChar);

    // Reset silence timer
    clearSilenceTimer();

    if (endsWithPunct || phraseBuffer.length >= PHRASE_MAX_CHARS) {
      flushPhrase();
    } else {
      silenceTimer = setTimeout(flushPhrase, PHRASE_SILENCE_MS);
    }
  }

  function flushPhrase() {
    clearSilenceTimer();
    const phrase = phraseBuffer.trim();
    phraseBuffer = "";
    if (!phrase || !isSigningActive) return;
    translateAndSign(phrase);
  }

  // ── Translation + signing ─────────────────────────────────────────────────
  async function translateAndSign(text) {
    setStatus("Translating…");

    // Route through background service worker to avoid CORS
    chrome.runtime.sendMessage({ type: "TRANSLATE", text }, (response) => {
      if (chrome.runtime.lastError) {
        console.warn("[DuoSign YT] Message error:", chrome.runtime.lastError.message);
        setStatus("Error");
        return;
      }

      if (!response?.ok) {
        console.warn("[DuoSign YT] Translation failed:", response?.error);
        setStatus("Error");
        return;
      }

      const data   = response.data;
      const tokens = data.tokens ?? data.gloss?.split(" ") ?? [];

      if (tokens.length === 0) {
        setStatus("Ready");
        return;
      }

      if (!posePlayer) {
        // Fallback: just show gloss text if player failed to init
        const el = document.getElementById("duosignPipGloss");
        if (el) el.textContent = tokens.join(" • ");
        setStatus("Ready");
        return;
      }

      // Queue tokens for signing (loops=1, plays once per phrase)
      posePlayer.playSequence(tokens, 1);

      // Also relay caption + tokens to side panel if open
      chrome.runtime.sendMessage({
        type: "YOUTUBE_CAPTION",
        text,
        tokens,
      });
    });
  }

  // ── Init ─────────────────────────────────────────────────────────────────
  async function init() {
    if (!window.location.pathname.startsWith("/watch")) return;

    const playerEl = await waitForPlayer();
    if (!playerEl) return;

    // Give YouTube captions a moment to appear
    setTimeout(() => {
      if (detectCaptions()) {
        createBanner(playerEl);
      } else {
        const poll = setInterval(() => {
          if (detectCaptions()) {
            createBanner(playerEl);
            clearInterval(poll);
          }
        }, 2000);
        setTimeout(() => clearInterval(poll), 30_000);
      }
    }, 2000);
  }

  // ── Handle YouTube SPA navigation ────────────────────────────────────────
  let lastUrl = window.location.href;
  new MutationObserver(() => {
    if (window.location.href === lastUrl) return;
    lastUrl = window.location.href;

    // Teardown
    if (captionObserver) { captionObserver.disconnect(); captionObserver = null; }
    if (posePlayer)      { posePlayer.stop(); posePlayer = null; }
    if (pipElement)      { pipElement.remove(); pipElement = null; }
    if (bannerElement)   {
      bannerElement.remove(); bannerElement = null;
      document.getElementById("duosign-yt-disclaimer")?.remove();
    }
    isSigningActive = false;
    lastCaption     = "";
    phraseBuffer    = "";
    clearSilenceTimer();

    if (window.location.pathname.startsWith("/watch")) init();
  }).observe(document.body, { childList: true, subtree: true });

  init();
})();
