/**
 * DuoSign Extension — YouTube Caption Interceptor & PiP Overlay
 * ==============================================================
 * Architecture:
 *   1. MutationObserver watches .ytp-caption-segment for live caption text
 *   2. Phrase buffer flushes on punctuation boundary OR 1.5s silence gap
 *   3. Buffered phrase → background (TRANSLATE) → ASL gloss tokens
 *   4. Pose files fetched via background (FETCH_POSE) to bypass CORS
 *   5. PosePlayer drives drawSkeleton on a fixed PiP canvas
 *   6. PiP is position:fixed → draggable across the entire YouTube page
 */

(function () {
  if (window.__duosignYT) return;
  window.__duosignYT = true;

  // ── Constants ─────────────────────────────────────────────────────────────
  const PHRASE_SILENCE_MS  = 1500;
  const PHRASE_MAX_CHARS   = 200;
  const PUNCTUATION_RE     = /[.?!;]/;
  const PIP_W_DEFAULT      = 260;
  const PIP_H_DEFAULT      = 320;
  const PIP_MIN_W          = 200;
  const PIP_MIN_H          = 240;
  const PIP_CHROME_H       = 54; // header (32) + footer (22)

  // IX-marker → gloss that has a real pose file
  const IX_MAP = {
    'IX':      'I',
    'IX-1':    'I',
    'IX-1+':   'WE',
    'IX-SELF': 'I',
    'IX-REFL': 'I',
    'IX-2':    'YOU',
    'IX-2+':   'YOU',
    'IX-3':    'THEY',
    'IX-3+':   'THEY',
    'IX-PL':   'WE',
    'IX-MULT': 'THEY',
    'IX-LOC':  'THERE',
  };

  // Resolve a raw backend token to a fetchable gloss name.
  // Returns null for tokens that should be dropped (numeric codes, empty, etc.)
  function resolveToken(token) {
    if (!token) return null;
    const t = token.trim().toUpperCase();
    if (!t) return null;
    if (t in IX_MAP) return IX_MAP[t];
    // Drop tokens that start with a digit — these are numeric codes, not glosses
    if (/^\d/.test(t)) return null;
    return t;
  }

  function displayToken(token) {
    return resolveToken(token) ?? token;
  }

  // ── State ─────────────────────────────────────────────────────────────────
  let captionObserver = null;
  let pipElement      = null;
  let bannerElement   = null;
  let toastElement    = null;
  let toastTimer      = null;
  let isSigningActive = false;
  let lastCaption     = "";
  let phraseBuffer    = "";
  let silenceTimer    = null;
  let posePlayer      = null;
  let pipCanvas       = null;
  let pipCtx          = null;
  let isDragging      = false;
  let dragOffsetX     = 0;
  let dragOffsetY     = 0;
  let isResizing      = false;
  let resizeStartX    = 0;
  let resizeStartY    = 0;
  let resizeStartW    = PIP_W_DEFAULT;
  let resizeStartH    = PIP_H_DEFAULT;
  let pipW            = PIP_W_DEFAULT;
  let pipH            = PIP_H_DEFAULT;
  const dpr           = window.devicePixelRatio || 1;

  // ── Utilities ─────────────────────────────────────────────────────────────
  function waitForPlayer() {
    return new Promise((resolve) => {
      const check = () => {
        const el = document.querySelector("#movie_player");
        if (el) return resolve(el);
        setTimeout(check, 500);
      };
      check();
    });
  }

  function detectCaptions() {
    const btn = document.querySelector(".ytp-subtitles-button");
    return btn != null;
  }

  function isAutoGenerated() {
    const tracks = document.querySelectorAll(".ytp-menuitem-label");
    for (const t of tracks) {
      if (t.textContent?.toLowerCase().includes("auto-generated")) return true;
    }
    return false;
  }

  function setStatus(text) {
    const el = document.getElementById("duosignPipStatus");
    if (el) el.textContent = text;
  }

  function clearSilenceTimer() {
    if (silenceTimer) { clearTimeout(silenceTimer); silenceTimer = null; }
  }

  // ── Detection banner ──────────────────────────────────────────────────────
  function createBanner(playerEl) {
    if (bannerElement) return;

    bannerElement = document.createElement("div");
    bannerElement.id = "duosign-yt-banner";
    bannerElement.innerHTML = `
      <div class="duosign-detect-icon">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>
        </svg>
      </div>
      <div class="duosign-detect-text">
        <strong>Captions detected</strong> — DuoSign can sign this video
      </div>
      <button class="duosign-detect-action" id="duosignStartBtn">Start Signing</button>
    `;

    const container =
      playerEl.closest("#player-container-outer") ||
      playerEl.closest("#player") ||
      playerEl.parentElement;

    if (container?.parentElement) {
      container.parentElement.insertBefore(bannerElement, container.nextSibling);
    }

    document.getElementById("duosignStartBtn").addEventListener("click", () => {
      if (isSigningActive) stopSigning();
      else startSigning(playerEl);
    });

    if (isAutoGenerated()) {
      const d = document.createElement("div");
      d.id = "duosign-yt-disclaimer";
      d.innerHTML = `
        <span class="duosign-warn-icon">⚠</span>
        <span>Auto-generated captions may contain inaccuracies that affect signing accuracy.</span>
      `;
      bannerElement.after(d);
    }
  }

  // ── Fixed toast (ambient-mode-safe fallback) ─────────────────────────────
  function createToast(playerEl) {
    if (toastElement) return;

    toastElement = document.createElement("div");
    toastElement.id = "duosign-toast";
    toastElement.innerHTML = `
      <span class="duosign-toast-icon">🤟</span>
      <div class="duosign-toast-body">
        <div class="duosign-toast-title">DuoSign ready</div>
        <div class="duosign-toast-sub">Captions detected</div>
      </div>
      <button class="duosign-toast-start" id="duosignToastStart">Start Signing</button>
      <button class="duosign-toast-close" id="duosignToastClose" title="Dismiss">×</button>
    `;
    document.body.appendChild(toastElement);

    document.getElementById("duosignToastStart").addEventListener("click", () => {
      if (isSigningActive) stopSigning();
      else startSigning(playerEl);
    });

    document.getElementById("duosignToastClose").addEventListener("click", removeToast);

    // Auto-dismiss after 12 s if the user ignores it
    toastTimer = setTimeout(removeToast, 12000);
  }

  function removeToast() {
    if (toastTimer) { clearTimeout(toastTimer); toastTimer = null; }
    if (toastElement) { toastElement.remove(); toastElement = null; }
  }

  function updateToastButton() {
    const btn = document.getElementById("duosignToastStart");
    if (!btn) return;
    if (isSigningActive) {
      btn.textContent = "Stop Signing";
      btn.classList.add("stopping");
    } else {
      btn.textContent = "Start Signing";
      btn.classList.remove("stopping");
    }
  }

  // ── PiP overlay ───────────────────────────────────────────────────────────
  // Attached to document.body with position:fixed so it floats over the whole
  // page. Default position aligns it roughly over the player bottom-right.
  function createPiP(playerEl) {
    if (pipElement) return;

    pipElement = document.createElement("div");
    pipElement.id = "duosign-pip";
    pipElement.innerHTML = `
      <div class="duosign-pip-header" id="duosignPipHeader">
        <div class="duosign-pip-label">
          <span class="duosign-pip-dot"></span>
          DuoSign
        </div>
        <button class="duosign-pip-btn" id="duosignPipClose" title="Close">×</button>
      </div>
      <div class="duosign-pip-canvas-wrap">
        <canvas id="duosignPipCanvas"></canvas>
        <div class="duosign-pip-idle" id="duosignPipIdle">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <circle cx="12" cy="8" r="4"/><path d="M4 20c0-4 3.6-7 8-7s8 3 8 7"/>
          </svg>
          <span>Waiting for captions…</span>
          <span class="duosign-pip-idle-hint">Enable CC on the video</span>
        </div>
      </div>
      <div class="duosign-pip-footer">
        <span class="duosign-pip-gloss" id="duosignPipGloss">—</span>
        <span class="duosign-pip-status" id="duosignPipStatus">Ready</span>
      </div>
      <div class="duosign-pip-resize" id="duosignPipResize"></div>
    `;

    // Default position: bottom-right, offset to sit above YouTube controls bar
    const playerRect = playerEl.getBoundingClientRect();
    pipElement.style.right  = `${window.innerWidth - playerRect.right + 16}px`;
    pipElement.style.bottom = `${window.innerHeight - playerRect.bottom + 60}px`;

    document.body.appendChild(pipElement);

    document.getElementById("duosignPipClose").addEventListener("click", stopSigning);
    document.getElementById("duosignPipHeader").addEventListener("mousedown", onDragStart);
    document.getElementById("duosignPipResize").addEventListener("mousedown", onResizeStart);

    pipCanvas = document.getElementById("duosignPipCanvas");
    _resizeCanvas(pipW, pipH);
  }

  // ── Canvas resize helper (applies DPR scaling) ───────────────────────────
  function _resizeCanvas(w, h) {
    const canvasH = h - PIP_CHROME_H;
    pipCanvas.width  = Math.round(w * dpr);
    pipCanvas.height = Math.round(canvasH * dpr);
    pipCanvas.style.width  = `${w}px`;
    pipCanvas.style.height = `${canvasH}px`;
    pipCtx = pipCanvas.getContext("2d");
    pipCtx.scale(dpr, dpr);
  }

  // ── Drag (page-level, position:fixed) ────────────────────────────────────
  function onDragStart(e) {
    if (!pipElement) return;
    isDragging  = true;
    const rect  = pipElement.getBoundingClientRect();
    dragOffsetX = e.clientX - rect.left;
    dragOffsetY = e.clientY - rect.top;
    pipElement.style.transition = "none";
    e.preventDefault();
  }

  // ── Resize ────────────────────────────────────────────────────────────────
  function onResizeStart(e) {
    if (!pipElement) return;
    isResizing   = true;
    resizeStartX = e.clientX;
    resizeStartY = e.clientY;
    resizeStartW = pipW;
    resizeStartH = pipH;
    e.preventDefault();
    e.stopPropagation();
  }

  document.addEventListener("mousemove", (e) => {
    if (isDragging && pipElement) {
      let x = e.clientX - dragOffsetX;
      let y = e.clientY - dragOffsetY;
      x = Math.max(0, Math.min(x, window.innerWidth  - pipW));
      y = Math.max(0, Math.min(y, window.innerHeight - pipH));
      pipElement.style.right  = "auto";
      pipElement.style.bottom = "auto";
      pipElement.style.left   = `${x}px`;
      pipElement.style.top    = `${y}px`;
    }
    if (isResizing && pipElement) {
      pipW = Math.max(PIP_MIN_W, resizeStartW + (e.clientX - resizeStartX));
      pipH = Math.max(PIP_MIN_H, resizeStartH + (e.clientY - resizeStartY));
      pipElement.style.width  = `${pipW}px`;
      pipElement.style.height = `${pipH}px`;
      _resizeCanvas(pipW, pipH);
    }
  });

  document.addEventListener("mouseup", () => {
    isDragging = false;
    isResizing  = false;
  });

  // ── PosePlayer — CORS-safe fetch via background ───────────────────────────
  // Content scripts cannot bypass CORS for binary fetches; route through the
  // background service worker's FETCH_POSE handler instead.
  function initPosePlayer() {
    if (posePlayer) return;

    if (typeof window.PosePlayer === "undefined" || typeof window.drawSkeleton === "undefined") {
      console.warn("[DuoSign YT] PosePlayer/drawSkeleton not available — check content script order");
      return;
    }

    posePlayer = new window.PosePlayer({
      onFrame(frame, header) {
        const idle = document.getElementById("duosignPipIdle");
        if (idle) idle.style.display = "none";
        const canvasH = pipH - PIP_CHROME_H;
        window.drawSkeleton(pipCtx, frame, header, pipW, canvasH);
      },
      onGlossChange(gloss) {
        const el = document.getElementById("duosignPipGloss");
        if (el) el.textContent = displayToken(gloss);
      },
      onComplete() {
        setStatus("Ready");
        const canvasH = pipH - PIP_CHROME_H;
        if (pipCtx) pipCtx.clearRect(0, 0, pipW, canvasH);
        const idle = document.getElementById("duosignPipIdle");
        if (idle) idle.style.display = "flex";
        const glossEl = document.getElementById("duosignPipGloss");
        if (glossEl) glossEl.textContent = "—";
      },
      onStateChange(state) {
        setStatus(
          state === "playing" ? "Signing…" :
          state === "paused"  ? "Paused"   : "Ready"
        );
      },
    });

    posePlayer.speed = 1.6;

    // ── Patch _fetchPose to route through background (avoids CORS in content scripts)
    posePlayer._fetchPose = async function (gloss) {
      const cached = this._poseCache.get(gloss);
      if (cached) return cached;

      return new Promise((resolve) => {
        chrome.runtime.sendMessage({ type: "FETCH_POSE", gloss }, (response) => {
          if (chrome.runtime.lastError || !response?.ok) {
            console.warn("[DuoSign YT] Pose fetch failed for", gloss, response?.error);
            resolve(null);
            return;
          }
          // background returns Array.from(Uint8Array) — convert back to ArrayBuffer
          const buf = new Uint8Array(response.data).buffer;
          this._parsePoseBuffer(buf, gloss).then((parsed) => {
            if (parsed) this._poseCache.set(gloss, parsed);
            resolve(parsed ?? null);
          });
        });
      });
    };
  }

  // ── Start / stop signing ──────────────────────────────────────────────────
  function startSigning(playerEl) {
    isSigningActive = true;

    const btn = document.getElementById("duosignStartBtn");
    if (btn) { btn.textContent = "Stop Signing"; btn.classList.add("active"); }

    // Cancel auto-dismiss and update toast button instead of removing it
    if (toastTimer) { clearTimeout(toastTimer); toastTimer = null; }
    updateToastButton();

    createPiP(playerEl);
    pipElement.style.display = "flex";
    initPosePlayer();
    startCaptionObserver();

    chrome.runtime.sendMessage({ type: "YOUTUBE_START" });
  }

  function stopSigning() {
    isSigningActive = false;
    clearSilenceTimer();

    const btn = document.getElementById("duosignStartBtn");
    if (btn) { btn.textContent = "Start Signing"; btn.classList.remove("active"); }

    updateToastButton();

    if (pipElement) pipElement.style.display = "none";
    if (captionObserver) { captionObserver.disconnect(); captionObserver = null; }
    if (posePlayer) posePlayer.stop();

    chrome.runtime.sendMessage({ type: "YOUTUBE_STOP" });
  }

  // ── Caption observer ──────────────────────────────────────────────────────
  function startCaptionObserver() {
    // Try multiple selectors YouTube uses across regions/versions
    const captionRoot =
      document.querySelector(".ytp-caption-window-container") ||
      document.querySelector(".captions-text") ||
      document.querySelector("[class*='caption-window']");

    if (!captionRoot) {
      if (isSigningActive) setTimeout(startCaptionObserver, 800);
      return;
    }

    captionObserver = new MutationObserver(() => {
      const segments = document.querySelectorAll(".ytp-caption-segment");
      let text = "";
      segments.forEach((s) => { text += s.textContent + " "; });
      text = text.trim();

      if (text && text !== lastCaption) {
        lastCaption = text;
        onCaptionChunk(text);
      }
    });

    captionObserver.observe(captionRoot, {
      childList: true,
      subtree: true,
      characterData: true,
    });
  }

  // ── Phrase buffering ──────────────────────────────────────────────────────
  function onCaptionChunk(text) {
    if (!isSigningActive) return;

    if (!phraseBuffer.endsWith(text)) {
      phraseBuffer = (phraseBuffer + " " + text).trim();
    }

    clearSilenceTimer();

    const lastChar      = phraseBuffer[phraseBuffer.length - 1];
    const endsWithPunct = PUNCTUATION_RE.test(lastChar);

    if (endsWithPunct || phraseBuffer.length >= PHRASE_MAX_CHARS) {
      flushPhrase();
    } else {
      silenceTimer = setTimeout(flushPhrase, PHRASE_SILENCE_MS);
    }
  }

  function flushPhrase() {
    clearSilenceTimer();
    const phrase = phraseBuffer.trim();
    phraseBuffer = "";
    if (!phrase || !isSigningActive) return;
    translateAndSign(phrase);
  }

  // ── Translate → sign ──────────────────────────────────────────────────────
  function translateAndSign(text) {
    setStatus("Translating…");

    chrome.runtime.sendMessage({ type: "TRANSLATE", text }, (response) => {
      if (chrome.runtime.lastError || !response?.ok) {
        console.warn("[DuoSign YT] Translation error:", chrome.runtime.lastError?.message ?? response?.error);
        setStatus("Error");
        return;
      }

      const data      = response.data;
      const rawTokens = data.tokens ?? data.gloss?.split(" ") ?? [];
      const tokens    = rawTokens.map(resolveToken).filter(Boolean);

      if (tokens.length === 0) { setStatus("Ready"); return; }

      // Show gloss in footer even if pose player isn't ready
      const glossEl = document.getElementById("duosignPipGloss");
      if (glossEl) glossEl.textContent = tokens.join(" · ");

      if (posePlayer) {
        posePlayer.playSequence(tokens, 1);
      } else {
        setStatus("Ready");
      }

      // Relay to side panel
      chrome.runtime.sendMessage({ type: "YOUTUBE_CAPTION", text, tokens });
    });
  }

  // ── Init ──────────────────────────────────────────────────────────────────
  async function init() {
    if (!window.location.pathname.startsWith("/watch")) return;

    const playerEl = await waitForPlayer();
    if (!playerEl) return;

    // Give YouTube a moment to render caption button
    setTimeout(() => {
      if (detectCaptions()) {
        createBanner(playerEl);
        createToast(playerEl);
      } else {
        const poll = setInterval(() => {
          if (detectCaptions()) {
            createBanner(playerEl);
            createToast(playerEl);
            clearInterval(poll);
          }
        }, 2000);
        setTimeout(() => clearInterval(poll), 30_000);
      }
    }, 2000);
  }

  // ── SPA navigation cleanup ────────────────────────────────────────────────
  let lastUrl = window.location.href;
  new MutationObserver(() => {
    if (window.location.href === lastUrl) return;
    lastUrl = window.location.href;

    if (captionObserver) { captionObserver.disconnect(); captionObserver = null; }
    if (posePlayer)      { posePlayer.stop(); posePlayer = null; }
    if (pipElement)      { pipElement.remove(); pipElement = null; pipW = PIP_W_DEFAULT; pipH = PIP_H_DEFAULT; }
    if (bannerElement)   {
      bannerElement.remove(); bannerElement = null;
      document.getElementById("duosign-yt-disclaimer")?.remove();
    }
    removeToast();

    isSigningActive = false;
    lastCaption     = "";
    phraseBuffer    = "";
    clearSilenceTimer();

    if (window.location.pathname.startsWith("/watch")) init();
  }).observe(document.body, { childList: true, subtree: true });

  init();
})();
