/**
 * DuoSign Extension — YouTube Overlay
 * ======================================
 * Content script injected on youtube.com/watch pages.
 * Detects captions, shows detection banner, injects PiP avatar overlay.
 */

(function () {
  // Guard against multiple injections
  if (window.__duosignYT) return;
  window.__duosignYT = true;

  const API_BASE_URL = "https://duosign.onrender.com";

  let captionObserver = null;
  let pipElement = null;
  let bannerElement = null;
  let isSigningActive = false;
  let captionQueue = [];
  let lastCaption = "";
  let pipCanvas = null;
  let pipCtx = null;
  let pipPlayer = null;

  // ── Wait for the YouTube player to load ─────────────────────────
  function waitForPlayer() {
    return new Promise((resolve) => {
      const check = () => {
        const player = document.querySelector("#movie_player");
        if (player) return resolve(player);
        setTimeout(check, 500);
      };
      check();
    });
  }

  // ── Detect captions ─────────────────────────────────────────────
  function detectCaptions() {
    // Check for caption track button or caption segments
    const captionBtn = document.querySelector(".ytp-subtitles-button");
    const hasCaptions =
      captionBtn && captionBtn.getAttribute("aria-pressed") !== undefined;
    return hasCaptions;
  }

  function isAutoGenerated() {
    // YouTube marks auto-generated captions — check the track list
    const tracks = document.querySelectorAll(".ytp-menuitem-label");
    for (const track of tracks) {
      if (
        track.textContent &&
        track.textContent.toLowerCase().includes("auto-generated")
      ) {
        return true;
      }
    }
    // Default: assume auto-generated for safety
    return true;
  }

  // ── Create detection banner ─────────────────────────────────────
  function createBanner(playerEl) {
    if (bannerElement) return;

    bannerElement = document.createElement("div");
    bannerElement.id = "duosign-yt-banner";
    bannerElement.innerHTML = `
      <div class="duosign-detect-icon">🔍</div>
      <div class="duosign-detect-text">
        <strong>Captions detected</strong> — English (auto-generated)
      </div>
      <button class="duosign-detect-action" id="duosignStartBtn">Start Signing</button>
    `;

    // Insert after the player
    const container =
      playerEl.closest("#player-container-outer") ||
      playerEl.closest("#player") ||
      playerEl.parentElement;
    if (container && container.parentElement) {
      container.parentElement.insertBefore(
        bannerElement,
        container.nextSibling,
      );
    }

    // Start button handler
    document.getElementById("duosignStartBtn").addEventListener("click", () => {
      if (isSigningActive) {
        stopSigning();
      } else {
        startSigning(playerEl);
      }
    });

    // Show disclaimer if auto-generated
    if (isAutoGenerated()) {
      const disclaimer = document.createElement("div");
      disclaimer.id = "duosign-yt-disclaimer";
      disclaimer.innerHTML = `
        <span class="duosign-warn-icon">⚠</span>
        <span>Auto-generated captions may contain inaccuracies. Sign language output may not perfectly match the speaker's intent.</span>
      `;
      bannerElement.after(disclaimer);
    }
  }

  // ── Create PiP overlay ──────────────────────────────────────────
  function createPiP(playerEl) {
    if (pipElement) return;

    pipElement = document.createElement("div");
    pipElement.id = "duosign-pip";
    pipElement.innerHTML = `
      <div class="duosign-pip-header">
        <div class="duosign-pip-label"><span class="duosign-pip-dot"></span> SIGNING</div>
        <button class="duosign-pip-close" id="duosignPipClose">×</button>
      </div>
      <div class="duosign-pip-canvas-wrap">
        <canvas id="duosignPipCanvas" width="320" height="320"></canvas>
      </div>
      <div class="duosign-pip-gloss" id="duosignPipGloss">Ready</div>
    `;

    playerEl.appendChild(pipElement);

    // Close button
    document.getElementById("duosignPipClose").addEventListener("click", () => {
      stopSigning();
    });

    // Setup canvas
    pipCanvas = document.getElementById("duosignPipCanvas");
    pipCtx = pipCanvas.getContext("2d");
  }

  // ── Start signing ───────────────────────────────────────────────
  function startSigning(playerEl) {
    isSigningActive = true;

    const startBtn = document.getElementById("duosignStartBtn");
    if (startBtn) startBtn.textContent = "Stop Signing";

    createPiP(playerEl);
    pipElement.style.display = "block";

    // Initialize PosePlayer for PiP
    // Note: PosePlayer and drawSkeleton are loaded via the extension's
    // content script context. We need to handle pose data manually here.
    startCaptionObserver();
  }

  function stopSigning() {
    isSigningActive = false;

    const startBtn = document.getElementById("duosignStartBtn");
    if (startBtn) startBtn.textContent = "Start Signing";

    if (pipElement) pipElement.style.display = "none";
    if (captionObserver) captionObserver.disconnect();

    // Send stop message
    chrome.runtime.sendMessage({ type: "YOUTUBE_STOP" });
  }

  // ── Caption Observer ────────────────────────────────────────────
  function startCaptionObserver() {
    // Observe caption segment changes
    const captionContainer =
      document.querySelector(".ytp-caption-window-container") ||
      document.querySelector(".caption-window");

    if (!captionContainer) {
      // Captions might not be visible yet — retry
      setTimeout(startCaptionObserver, 1000);
      return;
    }

    captionObserver = new MutationObserver(() => {
      const segments = document.querySelectorAll(".ytp-caption-segment");
      let fullCaption = "";
      segments.forEach((seg) => {
        fullCaption += seg.textContent + " ";
      });
      fullCaption = fullCaption.trim();

      if (fullCaption && fullCaption !== lastCaption) {
        lastCaption = fullCaption;
        onCaptionChange(fullCaption);
      }
    });

    captionObserver.observe(captionContainer, {
      childList: true,
      subtree: true,
      characterData: true,
    });
  }

  // ── Handle caption changes ──────────────────────────────────────
  async function onCaptionChange(text) {
    if (!isSigningActive) return;

    // Update gloss label
    const glossEl = document.getElementById("duosignPipGloss");

    try {
      // Translate the caption text
      const res = await fetch(`${API_BASE_URL}/api/translate/fast`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });

      if (!res.ok) return;
      const data = await res.json();
      const tokens = data.tokens || data.gloss.split(" ");

      if (tokens.length === 0) return;

      // Simple cycling display of gloss tokens in the PiP
      let i = 0;
      const interval = setInterval(() => {
        if (!isSigningActive || i >= tokens.length) {
          clearInterval(interval);
          return;
        }
        if (glossEl) glossEl.textContent = tokens[i];

        // Draw a simple signing indicator on the PiP canvas
        drawSimpleSkeleton(pipCtx, tokens[i]);
        i++;
      }, 600);

      // Also send to the side panel for full rendering
      chrome.runtime.sendMessage({
        type: "YOUTUBE_CAPTION",
        text: text,
      });
    } catch (err) {
      console.warn("[DuoSign YT] Translation error:", err);
    }
  }

  // ── Simple skeleton drawing for PiP ─────────────────────────────
  // Since the full pose player needs the pose-parser which isn't loaded
  // in the content script context, we draw a simplified animated skeleton
  function drawSimpleSkeleton(ctx, gloss) {
    if (!ctx) return;
    const w = 160,
      h = 160;
    ctx.clearRect(0, 0, w * 2, h * 2);
    ctx.save();

    const cx = w,
      cy = h;

    // Colors
    const bodyColor = "#5b8ef0";
    const handColor = "#2dd4bf";

    ctx.lineCap = "round";
    ctx.lineJoin = "round";

    // Head
    ctx.strokeStyle = bodyColor;
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(cx, cy - 40, 14, 0, Math.PI * 2);
    ctx.stroke();

    // Neck
    ctx.beginPath();
    ctx.moveTo(cx, cy - 26);
    ctx.lineTo(cx, cy - 15);
    ctx.stroke();

    // Shoulders
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(cx - 35, cy - 10);
    ctx.lineTo(cx + 35, cy - 10);
    ctx.stroke();

    // Spine
    ctx.beginPath();
    ctx.moveTo(cx, cy - 15);
    ctx.lineTo(cx, cy + 30);
    ctx.stroke();

    // Arms — randomize position slightly based on gloss hash
    const hash = gloss
      ? gloss.split("").reduce((a, c) => a + c.charCodeAt(0), 0)
      : 0;
    const leftArmAngle = -0.4 + (hash % 10) * 0.08;
    const rightArmAngle = 0.4 - (hash % 7) * 0.06;

    // Left arm
    const lElbowX = cx - 35 + Math.sin(leftArmAngle) * 25;
    const lElbowY = cy - 10 + Math.cos(leftArmAngle) * 25;
    ctx.beginPath();
    ctx.moveTo(cx - 35, cy - 10);
    ctx.lineTo(lElbowX, lElbowY);
    ctx.stroke();

    const lHandX = lElbowX + Math.sin(leftArmAngle - 0.3) * 22;
    const lHandY = lElbowY + Math.cos(leftArmAngle - 0.3) * 22;
    ctx.strokeStyle = handColor;
    ctx.beginPath();
    ctx.moveTo(lElbowX, lElbowY);
    ctx.lineTo(lHandX, lHandY);
    ctx.stroke();

    // Left fingers
    ctx.lineWidth = 1;
    for (let f = 0; f < 4; f++) {
      const angle = leftArmAngle - 0.6 + f * 0.3;
      ctx.beginPath();
      ctx.moveTo(lHandX, lHandY);
      ctx.lineTo(lHandX + Math.sin(angle) * 8, lHandY + Math.cos(angle) * 8);
      ctx.stroke();
    }

    // Right arm
    ctx.strokeStyle = bodyColor;
    ctx.lineWidth = 2;
    const rElbowX = cx + 35 + Math.sin(rightArmAngle) * 25;
    const rElbowY = cy - 10 + Math.cos(rightArmAngle) * 25;
    ctx.beginPath();
    ctx.moveTo(cx + 35, cy - 10);
    ctx.lineTo(rElbowX, rElbowY);
    ctx.stroke();

    const rHandX = rElbowX + Math.sin(rightArmAngle + 0.3) * 22;
    const rHandY = rElbowY + Math.cos(rightArmAngle + 0.3) * 22;
    ctx.strokeStyle = handColor;
    ctx.beginPath();
    ctx.moveTo(rElbowX, rElbowY);
    ctx.lineTo(rHandX, rHandY);
    ctx.stroke();

    // Right fingers
    ctx.lineWidth = 1;
    for (let f = 0; f < 4; f++) {
      const angle = rightArmAngle + 0.3 + f * 0.3;
      ctx.beginPath();
      ctx.moveTo(rHandX, rHandY);
      ctx.lineTo(rHandX + Math.sin(angle) * 8, rHandY + Math.cos(angle) * 8);
      ctx.stroke();
    }

    // Joints
    ctx.fillStyle = bodyColor;
    [
      [cx - 35, cy - 10],
      [cx + 35, cy - 10],
      [lElbowX, lElbowY],
      [rElbowX, rElbowY],
    ].forEach(([x, y]) => {
      ctx.beginPath();
      ctx.arc(x, y, 2.5, 0, Math.PI * 2);
      ctx.fill();
    });

    ctx.restore();
  }

  // ── Initialize ──────────────────────────────────────────────────
  async function init() {
    // Only run on watch pages
    if (!window.location.pathname.startsWith("/watch")) return;

    const playerEl = await waitForPlayer();
    if (!playerEl) return;

    // Wait a bit for captions to load
    setTimeout(() => {
      if (detectCaptions()) {
        createBanner(playerEl);
      } else {
        // Watch for captions becoming available
        const checkInterval = setInterval(() => {
          if (detectCaptions()) {
            createBanner(playerEl);
            clearInterval(checkInterval);
          }
        }, 2000);
        // Stop checking after 30 seconds
        setTimeout(() => clearInterval(checkInterval), 30000);
      }
    }, 2000);
  }

  // Handle YouTube SPA navigation
  let lastUrl = window.location.href;
  const urlObserver = new MutationObserver(() => {
    if (window.location.href !== lastUrl) {
      lastUrl = window.location.href;
      // Clean up previous state
      if (captionObserver) captionObserver.disconnect();
      if (pipElement) {
        pipElement.remove();
        pipElement = null;
      }
      if (bannerElement) {
        bannerElement.remove();
        bannerElement = null;
        const disclaimer = document.getElementById("duosign-yt-disclaimer");
        if (disclaimer) disclaimer.remove();
      }
      isSigningActive = false;
      lastCaption = "";

      // Re-init for new page
      if (window.location.pathname.startsWith("/watch")) {
        init();
      }
    }
  });
  urlObserver.observe(document.body, { childList: true, subtree: true });

  init();
})();
